
#include <avr\io.h>
#include "fafbox.h"


void initPorts(void) {
	CONTROL_DDR = 0xFF;
	CONTROL_PORT = (1<<HSYNC_PIN | 1<<VSYNC_PIN | 1<<WRITE_READ_ENABLE_PIN | 1<<BANK_SWITCH_PIN | 1<<PERIPHERAL_ENABLE_PIN | 1<<OUTPUT_ENABLE_PIN | 0<<SOUND_PIN | 1<<NETWORK_ENABLE_PIN);
	
	LOWER_ADDRESS_DDR = 0xFF;
	LOWER_ADDRESS_PORT = 0x00;
	HIGHER_ADDRESS_DDR = 0xFF;
	HIGHER_ADDRESS_PORT = 0x00;
	DATA_DDR = 0xFF;
	DATA_PORT = 0x00;
	
	GENERAL_STATUS_REGISTER = 0x00;
	CONTROLLER_STATUS_REGISTER = 0xFF; //no input
}